### ISSUE TITLE
In the Properties pages display Obligation and Cardinality in a new sub-section  

### ISSUE THREAD

**Issue by cyberdudeuk** [co-cddo/ukgov-metadata-exchange-model#51]
**Is your feature request related to a problem? Please describe.**
Currently the information on whether a property is Required (i.e. Mandatory) or Recommended, and its Cardinality is displayed as a line at the bottom of the first section (currently untitled) which contains the definition of the property, its URI and and the applicable range. It's somewhat easy to miss as it's slightly obscured by the preceding content. What is displayed for Obligation and Cardinality is actually a Boolean Value, i.e. True or False (in this case only those that are True).

**Describe the solution you'd like**
A clearer way for providing this information to make it more evident and visible would be to single it out into a separate section and replace the values by Yes or No, which might be more meaningful to a greater, more diverse range of users.

**Describe alternatives you've considered**
Creating a separate section is a neater, more user-friendly way of displaying this content, another option would be to make it Bold so it is more evident from the preceding content. The first option above however is the preferable outcome. It would be even better if the 2 values were shown in 2 separate boxes in just the one line, like a row in a table.

**Additional context**

1. These changes should also be reflected in the tables for each class with an additional column to display Obligation similar to the way Cardinality is already displayed.
2. This should also be implemented in the current home page in the Properties table just after the Description

**Comment by AlasdairGray** [comment]
In the current model the obligation of a property is not necessarily consistent across all usages of a property. For example, [`issued`](https://co-cddo.github.io/ukgov-metadata-exchange-model/issued/) is recommended for a [DataService](https://co-cddo.github.io/ukgov-metadata-exchange-model/DataService/) but optional for a [Dataset](https://co-cddo.github.io/ukgov-metadata-exchange-model/Dataset/).

It seems that the obligation is only shown if it is consistent across all usages but I don't see how this is programmed in the style sheet.

Testing with changing the cardinality did not seem to change whether the value is shown or not.

**Comment by AlasdairGray** [comment]
If we are happy to go with the current behaviour then we can easily put in a heading and put the information into a table. 

@cyberdudeuk Do you have a design in mind that you could sketch out?

For the theme property it could look something like the following

## Heading

| URL                                             | Range                                                                               | Obligation  | Cardinality |
|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------|-------------|
| [`dcat:theme`](http://www.w3.org/ns/dcat#theme) | [`Uriorcurie`](https://co-cddo.github.io/ukgov-metadata-exchange-model/Uriorcurie/) | Recommended | Many    |

**Comment by cyberdudeuk** [comment]
Yes that format is perfect

**Comment by AlasdairGray** [comment]
What text do you want for the heading or is just the table sufficient?

**Comment by cyberdudeuk** [comment]
Onligation and Cardinality so it stands out

**Comment by AlasdairGray** [comment]
How does the following look?
_Branch: https://github.com/co-cddo/ukgov-metadata-exchange-model/tree/issue-51_obligations_

Example with cardinality of one and mandatory:
![Screenshot 2023-10-26 at 10 47 58](https://github.com/co-cddo/ukgov-metadata-exchange-model/assets/1141265/77ea8e2e-a008-468b-8850-6e1cec55d7a6)

Example with cardinality of many:
![Screenshot 2023-10-26 at 10 48 59](https://github.com/co-cddo/ukgov-metadata-exchange-model/assets/1141265/b231e13c-4b94-4f7a-a6a1-897b42bff0c2)

Example with a regular expression pattern:
![Screenshot 2023-10-26 at 10 49 33](https://github.com/co-cddo/ukgov-metadata-exchange-model/assets/1141265/a0e1c7f8-e7f5-4b85-8824-99b1623e916a)

Example with a minimum value (we don't have any maximum values set but it would work the same):
![Screenshot 2023-10-26 at 10 50 19](https://github.com/co-cddo/ukgov-metadata-exchange-model/assets/1141265/d49063c4-92db-4e1f-bd44-59ab23158171)

Example with an obligation of optional:
![Screenshot 2023-10-26 at 10 51 28](https://github.com/co-cddo/ukgov-metadata-exchange-model/assets/1141265/1b9d5873-f9a0-402e-9f2c-61493472bdff)

**Comment by cyberdudeuk** [comment]
It looks much better 🙂👍
