### ISSUE TITLE
Minimal examples on Distribution page result in 404 errors

### ISSUE THREAD

**Issue by AlasdairGray** [co-cddo/ukgov-metadata-exchange-model#59]
**Describe the bug**
A 404 Not found error is returned when clicking on either the [Distribution-os-postcodes-csv-distribution-minimal](https://co-cddo.github.io/ukgov-metadata-exchange-model/Distribution/assets/examples/Distribution-os-postcodes-csv-distribution-minimal.yaml.json) or the [Distribution-os-postcodes-excel-distribution-minimal](https://co-cddo.github.io/ukgov-metadata-exchange-model/Distribution/assets/examples/Distribution-os-postcodes-excel-distribution-minimal.yaml.json) examples.

**To Reproduce**
1. Go to 'https://co-cddo.github.io/ukgov-metadata-exchange-model/Distribution/#examples'
2. Click on '[Distribution-os-postcodes-csv-distribution-minimal](https://co-cddo.github.io/ukgov-metadata-exchange-model/Distribution/assets/examples/Distribution-os-postcodes-csv-distribution-minimal.yaml.json)'
3. See 404 Not found error

**Expected behavior**
The JSON representation of the example should be displayed.

**Screenshots**
![Screenshot 2023-10-30 at 14 43 04](https://github.com/co-cddo/ukgov-metadata-exchange-model/assets/1141265/59932a0b-e6b8-4683-8013-1f9ebf5e4b61)

![Screenshot 2023-10-30 at 14 42 34](https://github.com/co-cddo/ukgov-metadata-exchange-model/assets/1141265/020bd1bd-4373-40ab-8b7f-87d233ec6ac7)

**Additional context**
This relates to an underlying problem in the LinkML framework that has been reported in https://github.com/linkml/linkml/issues/1508

**Comment by soydaner** [comment]
I could not reach the enum values as well. They returned 404 page. Are those having the same/similar issue?

https://co-cddo.github.io/ukgov-metadata-exchange-model/OrganisationValues/OrganisationValues
https://co-cddo.github.io/ukgov-metadata-exchange-model/AccessRightsValues/AccessRightsValues
https://co-cddo.github.io/ukgov-metadata-exchange-model/SecurityClassificationValues/SecurityClassificationValues
etc.

**Comment by AlasdairGray** [comment]
> I could not reach the enum values as well. They returned 404 page. Are those having the same/similar issue?
> 
> https://co-cddo.github.io/ukgov-metadata-exchange-model/OrganisationValues/OrganisationValues https://co-cddo.github.io/ukgov-metadata-exchange-model/AccessRightsValues/AccessRightsValues https://co-cddo.github.io/ukgov-metadata-exchange-model/SecurityClassificationValues/SecurityClassificationValues etc.

No those are not related to this issue. Each of your URLs has an extra directory on the end, they should be
- https://co-cddo.github.io/ukgov-metadata-exchange-model/OrganisationValues/
- https://co-cddo.github.io/ukgov-metadata-exchange-model/AccessRightsValues/
- https://co-cddo.github.io/ukgov-metadata-exchange-model/SecurityClassificationValues/

**Comment by soydaner** [comment]
I see, that's OK. Then let me explain what happened in my case: there is a link for non existent page.
I open this page: https://co-cddo.github.io/ukgov-metadata-exchange-model/OrganisationValues/
then click the URI: link and end with this page (404):
https://co-cddo.github.io/ukgov-metadata-exchange-model/OrganisationValues/OrganisationValues

**Comment by AlasdairGray** [comment]
In order to get the examples displaying, and to work within the LinkML assumptions, we will need to change the way that we are defining the classes so that we start with the least restrictive and then increase the obligation. 

This would mean that the property page would show the least restrictive usage rather than the common usage of the property. To overcome this, we propose to extract the URI value and place it a consistent position with the class pages and merge the Obligation and Cardinality table with the Applicable Classes table so that it would look something like the following

URI: [`accessRights`](dcat:accessRights)
| Class                 | Range                                                                               | Obligation  | Cardinality |
|-----------------------|-------------------------------------------------------------------------------------|-------------|-------------|
| [`Data Resource`](/DataResource) | [`Uriorcurie`](https://co-cddo.github.io/ukgov-metadata-exchange-model/Uriorcurie/) | Recommended | Multiple    |
| [`Distribution`](/Distribution) | [`Uriorcurie`](https://co-cddo.github.io/ukgov-metadata-exchange-model/Uriorcurie/) | Optional | Multiple    |
| [`Data Service`](/DataService) | [`Uriorcurie`](https://co-cddo.github.io/ukgov-metadata-exchange-model/Uriorcurie/) | Recommended | Multiple    |
| [`Dataset`](/Dataset) | [`Uriorcurie`](https://co-cddo.github.io/ukgov-metadata-exchange-model/Uriorcurie/) | Recommended | Multiple    |
