### ISSUE TITLE
Add more relevant support info to 404 error msg 

### ISSUE THREAD

**Issue by cyberdudeuk** [co-cddo/ukgov-metadata-exchange-model#67]
**Is your feature request related to a problem? Please describe.**
Currently no information or contact info is provided when an error msg occurs on a page.

**Describe the solution you'd like**
Add a feedback link so the team can deal w/ the issue if possible using the Bug template in GitHub for users to log it.

**Comment by AlasdairGray** [comment]
I have found out how to serve a custom 404 page. Could you provide the content that you want on it?

**Comment by AlasdairGray** [comment]
Initial draft of 404 page developed on branch https://github.com/co-cddo/ukgov-metadata-exchange-model/tree/issue-67/404-page. Extended text found on gov.uk 404 page.

![Screenshot 2023-11-03 at 16 02 27](https://github.com/co-cddo/ukgov-metadata-exchange-model/assets/1141265/f72d7804-90ea-4aff-8ed0-1c02d8f7e47d)
